version: "3.8"

services:
  frontend:
    image: evoapicloud/evo-ai-frontend:latest
    
    ports:
      - "3000:3000"
    environment:
      
      NEXT_PUBLIC_API_URL: http://192.168.1.74:8000

    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
   
networks:
  app_network:
    external: true
